<?php
/**
 * 
 *
 * @author EpicDewd
 * @version 1.0
 * @copyright HalpMeh, 11 November, 2010
 * @package 4chan
 **/
class Install 
{
	function __construct()
	{
		# Construct Function
	}
	function __destruct()
	{
		# Destruct Function
	}
	function Done()
	{
		# Stops the script.
		return false;
	}
	function HTML()
	{
	# Just echos the html.  Used to keep things cleaner.
			echo <<<HTML
			<!DOCTYPE html>
			<html>
				<head>
					<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
					<title>
						Install
					</title>
					<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript"></script>
					<script src="main.js" type="text/javascript"></script>
					<link rel="stylesheet" href="main.css" type="text/css" />
				</head>
				<body>
					<h1>
						Install
					</h1>
					<h2>
						Database Info
					</h2>
					<form action="?" method="post">
						<div class="input">
							<input type="text" class="cool" name="host" value="SQL Host" />
						</div>
						<div class="input">
							<input type="text" class="cool" name="user" value="SQL User" />
						</div>
						<div class="input">
							<input type="text" class="cool" name="pass" value="SQL Pass" />
						</div>
						<div class="input">
							<input type="text" class="cool" name="name" value="SQL DBName" />
						</div>
						<input type="hidden" name="areWeHere" value="Yes!" />
						<div class="input">
							<input type="submit" class="cool" name="Submit" value="Install!" />
						</div>
					</form>
				</body>
			</html>
HTML;
	}
	function Generate($host, $user, $pass, $name)
	{
		if($writer = @fopen("Config.php", "a+"))
		{
			fwrite($writer, "\n\n\$host = '$host';\n\$user = '$user';\n\$pass = '$pass';\n\$name = '$name';\n\n# File generated by OjoBB\n\n?>");
			fclose($writer);
			echo <<<HTML
			<h1>
				Success!
			</h1>
			<h2>
				Install Completed!
			</h1>
			<p>
				You will now be redirected back home
			</p>
			<!-- Redirect Code Goes Here. -->
HTML;
		}
		# If the writing to the file fails.
		else
		{
			echo <<<HTML
		<h2>
			Config File
		</h2>
		<p>
			Unfortunately we were unable to write to your config file (config.php).  You may chmod it to 777 and re-try or paste this code into the bottom of config.php.
		</p>
HTML;
	echo "\$host = '$host'; <br />";
	echo "\$user = '$user'; <br />";
	echo "\$pass = '$pass'; <br />";
	echo "\$name = '$name'; <br />";
	echo "?>";

		}
	}
}
?>
